### ISSUE TITLE
Result.DecodeField() doesn't work when requesting url datas

### ISSUE THREAD

**Issue by gouy-elliot** [huandu/facebook#102]
Hi there,

I have an error when decoding field when ids are urls. Take a look at this graph request:
`https://graph.facebook.com/v2.12/?ids=https://google.com/,https://youtube.com/&fields=id,engagement&access_token=MY_ACCESS_TOKEN`

The result looks like this:
```
{
    "https://google.com/": {
        "id": "https://google.com/",
        "engagement": {
            "reaction_count": 1279003,
            "comment_count": 233082,
            "share_count": 3411235,
            "comment_plugin_count": 404
        }
    },
    "https://youtube.com/": {
        "id": "https://youtube.com",
        "engagement": {
            "reaction_count": 13693288,
            "comment_count": 1086738,
            "share_count": 6889028,
            "comment_plugin_count": 67
        }
    }
}
```

The error come from the "." in the urls, is there anyway I can escape those characters before calling Result.DecodeField() ?

Thx,
Elliot.

**Comment by huandu** [comment]
And as you may know, `Result` is a `map[string]interface{}`. It's ok to use result as a map.

**Comment by gouy-elliot** [comment]
Awesome. Thanks 👍 !
