### ISSUE TITLE
No way to override API base URL

### ISSUE THREAD

**Issue by vania-pooh** [huandu/facebook#104]
Currently request is always being to sent to real Facebook Graph API. In order to cover features by unit tests I would point this client library to a mock implementation with predefined responses. So basically it would be great to have something like:
```
        var facebookMockSrv = httptest.NewServer(testMux)
	session := &fbclient.Session{
		Version:    "v3.0",
		HttpClient: someHttpClient,
                BaseUrl: facebookMockSrv.URL, //e.g. http://127.0.0.1:53456
	}
```
In that case this client should use provided base URL instead of `https://graph.facebook.com/`.

**Comment by vania-pooh** [comment]
@huandu I could send a PR if this feature seems to be reasonable for you.

**Comment by huandu** [comment]
It sounds reasonable.

If you can send a PR, please remember to add a use case in README. Thanks.

**Comment by vania-pooh** [comment]
Here is my PR: https://github.com/huandu/facebook/pull/105
