### ISSUE TITLE
Unknown path components

### ISSUE THREAD

**Issue by karolispx** [huandu/facebook#116]
Hey,

I've used this library for a week and it worked great. Last Thursday it just stopped working and I'm unable to make it work again. I worked on 'hello_world' project, then switched to another project to test out some code in Visual studio code 2, then switched back to the actual project and it just stopped working.

Here's my stripped down code:

```
package main

import (
	"fmt"
	fb "github.com/huandu/facebook"
)

func main() {
	fb.Version = "3.1"

	res, _ := fb.Get("/me/adaccounts", fb.Params{
		"fields":       "id,name,currency",
		"access_token": "my actual token",
	})

	fmt.Println(res)
}
```

And here's the error I'm getting: 
`map[error:map[fbtrace_id:DCVz8na9Pri message:Unknown path components: /me/adaccounts type:OAuthException code:2500] __usage__:0xc0002dc090]`

I've tried changing the token (gives error relating to the token), tested the token using fb debug - token is definitely valid and is working in the app written in PHP. Also tested it using CURL and net/http package - everything works fine. 

Any idea what could be causing this? It's weird that it just stopped working when I switched the projects. 

Thanks,
Karolis.

**Comment by huandu** [comment]
I cannot reproduce your issue. I write a test case and it works fine.

The most possible cause is that you misspelled `adccounts` in your code. Please check it.

**Comment by huandu** [comment]
See https://github.com/huandu/facebook/blob/e344d22ede2e56e440409a185063808dde25a649/api_test.go#L151-L170

**Comment by karolispx** [comment]
Thanks!

I was redoing my code to use http.Get and was testing CURL requests and have encountered the same issue a couple of times, and I realised I forgot to include 'v' with the version.

The issue was with the fb.Version = "3.1", it should've been fb.Version = "v3.1" (as mentioned in your code, I must've removed it by an accident.
