### ISSUE TITLE
how to upload photos on facebook using this SDK ? 

### ISSUE THREAD

**Issue by malavp123** [huandu/facebook#122]
I tried using facebook API directly but it is too damn complex and I cannot do it anymore.  I'm a novice on GoLang please help me to publish photo on facebook using this sdk

**Comment by huandu** [comment]
You can follow this facebook doc [Uploading Photos and publishing Photo stories in Graph API](https://developers.facebook.com/docs/graph-api/photo-uploads).

Here is a sample to translate from cURL to Go code.

```shell
curl -i -X POST \
  -d "url=https://www.facebook.com/images/fb_icon_325x325.png" \
  -d "caption=test photo upload" \
  -d "access_token=<page_access_token>" \
  "https://graph.facebook.com/v2.11/<page_id>/photos"
```

```go
res, err := facebook.Post("/<page_id>/photos", facebook.Params{
    "url": "https://www.facebook.com/images/fb_icon_325x325.png",
    "caption": "test photo upload",
    "access_token": "<page_access_token>",
})
```

**Comment by snowsmoky1** [comment]
Thanks

**Comment by huandu** [comment]
Feel free to reopen it if you still have any question.

**Comment by mmaedel** [comment]
hi huandu

thats the response error I get ?!

map[__usage__:0xc000264210 error:map[code:200 fbtrace_id:A9RoePYE5gYXKvCTgoyy5aE message:(#200) The permission(s) publish_actions are not available. It has been deprecated. If you want to provide a way for your app users to share content to Facebook, we encourage you to use our Sharing products instead. type:OAuthException]]

wher to go next...

greetings

**Comment by huandu** [comment]
@mmaedel Facebook deprecated `publish_actions` permission for years. It's not possible to acquire a user token and publish content on behalf of a user. It's recommended to use [Sharing SDK](https://developers.facebook.com/docs/sharing) and ask users to share content themselves.

**Comment by mmaedel** [comment]
ok thanks
