### ISSUE TITLE
Array parameters in request

### ISSUE THREAD

**Issue by patrikhermansson** [huandu/facebook#123]
I'm trying to use the library to access the [Ad library API](https://developers.facebook.com/docs/marketing-api/reference/ads_archive/ ) but can't figure out how to supply an array field as is required which results in it giving me an "Invalid parameter" error. I've successfully used the same access token and parameters in a curl request.

Here's an example of the parameters failing. I can't seem to find anything mentioning array parameters in the documentation.

`res, err := fb.Get("/v3.2/ads_archive", fb.Params{
		"ad_reached_countries": []string{"GB", "US"},
		"access_token": accesstoken,
	})`

**Comment by huandu** [comment]
It should be a bug. I'll fix it soon in a week.

**Comment by patrikhermansson** [comment]
Thanks for your quick reply. I have actaully managed to solve the issue and it's not an error with this library. The only issue was that I was missing another parameter that was apparently required. Using pure curl gave me clearer error messages, so if anything it's just that error messages are unclear in this library!

**Comment by huandu** [comment]
Glad to hear that. I thought it was a JSON encoding error but actually not. Thanks for your clarification.

@patrikhermansson Can you please post the error message you got by this package and the message from curl? I'd like to know why these two messages were not the same.

**Comment by huandu** [comment]
Glad to hear that. I thought it was a JSON encoding error but actually not. Thanks for your clarification.

@patrikhermansson Can you please post the error message you got by this package and the message from curl? I'd like to know why these two messages were not the same.

**Comment by huandu** [comment]
Glad to hear that. I thought it was a JSON encoding error but actually not. Thanks for your clarification.

@patrikhermansson Can you please post the error message you got by this package and the message from curl? I'd like to know why these two messages were not the same.

**Comment by huandu** [comment]
Glad to hear that. I thought it was a JSON encoding error but actually not. Thanks for your clarification.

@patrikhermansson Can you please post the error message you got by this package and the message from curl? I'd like to know why these two messages were not the same.

**Comment by huandu** [comment]
Glad to hear that. I thought it was a JSON encoding error but actually not. Thanks for your clarification.

@patrikhermansson Can you please post the error message you got by this package and the message from curl? I'd like to know why these two messages were not the same.
