### ISSUE TITLE
doc mentions outdated graph api version numbers

### ISSUE THREAD

**Issue by dankegel** [huandu/facebook#124]
The doc starts out "Package facebook is a Go library fully supports Facebook Graph API (both 1.0 and 2.x) "

Probably want to drop the version specifier, since 1.0 is EOL
( https://developers.facebook.com/docs/graph-api/changelog )
and new apps are already using 3.x?

**Comment by huandu** [comment]
I see. I should change this sentence. Actually, this package works with 1.x, 2.x or 3.x or even N.x. The version number doesn't matter at all.
