### ISSUE TITLE
How to test/mock default session?

### ISSUE THREAD

**Issue by Fryyyyy** [huandu/facebook#125]
Hi

I have a single call that I need to make where I do not want the access_token parameter set, thus I do this one particular call with a raw api.Post rather than a session.Post
Is there a way to get access to the defaultSession and change the baseURL ?

**Comment by huandu** [comment]
You can set `BaseURL` in `Session` to change base URL as you expected.

See [Session](https://godoc.org/github.com/huandu/facebook#Session) and #104.

**Comment by Fryyyyy** [comment]
Yeah that's for a constructed session, but not for the defaultSession that is used if you do something like
```
app := fb.New(...)
app.Post(...
```

**Comment by huandu** [comment]
If you call `Post` on a `Session` instance, you can do following. Note that you don't need to set access token in `Session`.

```go
session := fb.Session{
    BaseURL: "xxxx",
}
session.Post(...)
```

If you want to use `App` to create a session, it's OK to create a session without access token.

```go
app := fb.New(...)
session := app.Session("") // Empty access token.
session.BaseURL = "..." // For test.
session.Post(...)
```

**Comment by Fryyyyy** [comment]
Ah, okay. Cool, thanks.

**Comment by huandu** [comment]
😄 

If you still have any question, feel free to reopen this issue.
