### ISSUE TITLE
Get DebugInfo and UsageInfo on PagingResult

### ISSUE THREAD

**Issue by OwlLaboratory** [huandu/facebook#126]
It is, at the moment, not possible to get DebugInfo or UsageInfo from a request made using PagingResult.Next() method.

I need this to check the Ad Account rate limit within my `for` loop.
Example:
```golang
var app = fb.New("MY_APP_ID", "MY_APP_SECRET")
var session = app.Session("MY_TOKEN")

session.SetDebug(fb.DEBUG_ALL)

result, _ := session.Get("/MY_AD_ACCOUNT_ID/activities", fb.Params{
    "fields": "event_time,event_type,object_id,object_type",
    "limit": 100,
})
// Here I can call result.DebugInfo() to check to first request only
paging, _ := res.Paging(session)

noMore := false
for !noMore {
    var results = paging.Data()
    // Do something with the data

    // Check the X-Ad-Account-Usage header before making the next request -> not possible
    noMore, _ = paging.Next()
}
```

P.S: Since v3.3 a [new rate limit header](https://developers.facebook.com/docs/marketing-api/best-practices/#adsoverview) `X-Ad-Account-Usage` has been added for request made on the Marketing API, it would be great to add it in the UsageInfo struct too.

Regards

**Comment by huandu** [comment]
`DebugInfo` and `UsageInfo` are fields in `Result`, while the new rate limit header is stored in response header. From my understanding, you're asking for a new API in `PageResult` to get current page's rate limit information in response header.

Correct me if I didn't read right. This feature is not complex. I can do it in a few days after I get your confirmation.

**Comment by OwlLaboratory** [comment]
Exactly, you got this right, having something like `paging.DebugInfo()` to get the rate limit information of the last request made.

Thanks.

**Comment by huandu** [comment]
Got it.
