### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by gaste11o** [huandu/facebook#155]
Hello!
Is it possible to add proxy support?

**Comment by huandu** [comment]
It's supported.

There is a field named `HttpClient` in [type `Session`](https://pkg.go.dev/github.com/huandu/facebook?tab=doc#Session). You can replace it to an HTTP client with proxy enabled. If you want to change the client of default `Session` which is used in func `Get`/`Post`/`Api`/etc., call [func `SetHttpClient`](https://pkg.go.dev/github.com/huandu/facebook?tab=doc#SetHttpClient).

**Comment by gaste11o** [comment]
Many thanks. You were very helpful.
