### ISSUE TITLE
Support for Send API?

### ISSUE THREAD

**Issue by Abdaaf** [huandu/facebook#166]
Will this SDK have support for the Messaging/Send api (in the future)? Like a wrapper.

**Comment by huandu** [comment]
Do you mean this https://developers.facebook.com/docs/messenger-platform/reference/send-api?

If so, there is no plan to develop a specific API for it. You can use `Post()` to send message.

Here is a quick sample.

```go
facebook.Post("/me/messages", facebook.Params{
  "messaging_type": "<MESSAGING_TYPE>",
  "recipient": {
    "id": "<PSID>",
  },
  "message": {
    "text": "hello, world!",
  },
})
```

**Comment by Abdaaf** [comment]
Yes. An implementation for the send and other API's. I forked the project and will build it for my use case. The sample is indeed how it should work:

```
func (session *Session) SendTextMessage(psid string, text string) (res Result, err error) {
	body := SendBody{
		Recipient: &Recipient{
			ID: psid,
		},
		Message: &Message{
			Text: text,
		},
	}

	res, err = session.Post("me/messages", MakeParams(body))
	return
}
```

**Comment by huandu** [comment]
I recommend you to implement this in your business package. This package shouldn't include any Graph API data structure.
