### ISSUE TITLE
Json body versus urlencoded

### ISSUE THREAD

**Issue by bayoumymac** [huandu/facebook#172]
Hello,

Thank you so much for the great adapter, I had a question regarding the reasoning behind combining both the request body and params into a urlencoded string in the body for POST requests versus just keeping them separate, in other words "application/x-www-form-urlencoded" vs "application/json" for ContentType

**Comment by zawzawaung-prog** [comment]
😁

**Comment by huandu** [comment]
This is a classic way to send Graph API requests since the first version of Graph API. As it still works well, I don't have any reason to change it.

**Comment by huandu** [comment]
Close it due to no response for 1 week. Feel free to add comment or re-open this issue if you have more questions. @bayoumymac
