### ISSUE TITLE
paging.UsageInfo().App nil pointer dereference

### ISSUE THREAD

**Issue by uginroot** [huandu/facebook#176]
After calling result.Paging(), the UsageInfo property is not initialized.

When you call result.Paging(), the UsageInfo property is not copied, and when you call paging.Next(), it is copied, it seems it should be copied even when result.Paging().

result.Paging() https://github.com/huandu/facebook/blob/5c41bb9c54f2a2f5505f607deeaf582caa37714f/paging_result.go#L35
paging.Next() https://github.com/huandu/facebook/blob/5c41bb9c54f2a2f5505f607deeaf582caa37714f/paging_result.go#L153

What do you think about it?

**Comment by huandu** [comment]
See https://github.com/huandu/facebook/blob/master/paging_result.go#L45. The `UsageInfo` should have been initialized by `res.Decode`.

```go
pr := &PagingResult{
    session: session,
}
paging := &pr.paging
err := res.Decode(paging) // UsageInfo should be initialized in this call.
```

**Comment by huandu** [comment]
I just get your point. Yes, you are right. The `paging.UsageInfo` should be set. It's a bug.
