### ISSUE TITLE
Handling of paging and access tokens

### ISSUE THREAD

**Issue by partomatl** [huandu/facebook#182]
Hi, thanks for the work on this repo 🙂

https://github.com/huandu/facebook/blob/01c37fb1e39ea2c7024e344374cfebc2c5d79ec6/paging_result.go#L110-L131

If `pr.session.accessToken` is not empty, `pr.session.prepareParams(params)` adds it to `params` (which is always empty because of the `params := Params{}` line just above) :

https://github.com/huandu/facebook/blob/01c37fb1e39ea2c7024e344374cfebc2c5d79ec6/session.go#L431-L434

The `pr.session.accessToken` is then appended to the query string of the `next` (or `previous`) URL returned by the API. 

If an `access_token` parameter was already present in the URL, then two things can happen:
1. the first `access_token` was the `session`'s token, in that case the `session`'s token is now twice in the URL. The API call still works.
2. the first `access_token` was not the `session`'s token and in that case the API call can fail. For instance the first token could be a [page access token](https://developers.facebook.com/docs/facebook-login/guides/access-tokens#pagetokens). Then the API will return a `(#210) A page access token is required to request this resource` error.

Maybe I'm missing something but I don't think any work needs to be done on the `next` (or `previous`) URL returned by the API. It should already hold all the parameters of the initial API call.
What do you think?

**Comment by huandu** [comment]
You're right. It's not necessary (or wrong) to add an extra access_token in prev/next url. I can fix it soon.

**Comment by huandu** [comment]
Fixed this issue in v2.5.6.
