### ISSUE TITLE
Could you enable "Private vulnerability reporting" or something equivalent?

### ISSUE THREAD

**Issue by seiyab** [huandu/facebook#235]
I've encounterd a problem related to this module and possibly we can consider it to be vulnerability. Could you specify a place where we can discuss security issue?
<img width="500" alt="Screenshot 2024-05-14 at 17 04 03" src="https://github.com/huandu/facebook/assets/20365512/7ec5f10e-6bec-4443-98ea-fab6cbbc5639">

**Comment by huandu** [comment]
@seiyab Thanks for your reminder. The private vulnerability reporting feature is enabled now.

**Comment by seiyab** [comment]
@huandu 
Thank you, I reported it. Feel free to ask me more information in advisory.
