### ISSUE TITLE
the project is still alive?

### ISSUE THREAD

**Issue by Allan-Nava** [huandu/facebook#243]

**Comment by huandu** [comment]
Sure.

**Comment by huandu** [comment]
It should work well on latest Graph API v20.

**Comment by Allan-Nava** [comment]
Is possible to upload a video and create a post for instagram?

**Comment by Allan-Nava** [comment]
> @Allan-Nava Yes. You can follow [this link](https://developers.facebook.com/docs/instagram-platform/instagram-graph-api/content-publishing/) to publish content. If you need to upload files, you can use [BinaryFile](https://pkg.go.dev/github.com/huandu/facebook/v2#BinaryFile) to wrap file in API.

Ok thanks for the support! Now i will try
