### ISSUE TITLE
CamelCase on ID should be _id

### ISSUE THREAD

**Issue by afinkenstadt** [huandu/facebook#25]
`go lint` complains about how `UserId` should be `UserID`.  The current implementation converts `UserID` to `user_i_d`, and `ID` to `i_d`.  Facebook, of course, wants `id` on its fields.

We work around this now using the back-tick decorator to force the fieldname to the correct underscore'd JSON name.  It would be nice to just do it automatically, and make huandu/facebook friendly with `golint`.

**Comment by huandu** [comment]
I also feel it should be `id` rather than `i_d`. I'll fix it soon.

**Comment by huandu** [comment]
Oh, wait... I found this issue should have been fixed by #24.

@afinkenstadt Can you get latest source code and try again?

**Comment by afinkenstadt** [comment]
I will, and it'll be tomorrow.

**Comment by afinkenstadt** [comment]
Confirmed, 1.4 fixes the issue.
