### ISSUE TITLE
feat: use AuthorizationType while setting the token into http header

### ISSUE THREAD

**Issue by 21hs** [huandu/facebook#253]
,

**Comment by huandu** [comment]
What's `AuthorizationType`?

**Comment by 21hs** [comment]
In software development, particularly in the context of APIs, AuthorizationType usually refers to the mechanism or method used to control access to resources or endpoints. It specifies how the system verifies the identity and permissions of the user or system making a request. Understanding AuthorizationType is essential for securing APIs and services.

Here’s an overview of common AuthorizationType values:

1. NONE
Description: No authorization is required.
Use Case: This is used for publicly accessible APIs where no authentication is needed. Any client can access these endpoints without restrictions.
Example: An API endpoint that provides general information like weather data or public content.
2. API_KEY
Description: The client includes an API key in the request headers or URL parameters.
Use Case: Commonly used for identifying applications rather than users. It's a simple way to control access and monitor usage but lacks fine-grained access control.
Example:
GET /resource HTTP/1.1
x-api-key: your-api-key-here

**Comment by 21hs** [comment]
> O que é `AuthorizationType`?

No desenvolvimento de software, particularmente no contexto de APIs, AuthorizationType geralmente se refere ao mecanismo ou método usado para controlar o acesso a recursos ou endpoints. Ele especifica como o sistema verifica a identidade e as permissões do usuário ou sistema que faz uma solicitação. Entender AuthorizationType é essencial para proteger APIs e serviços.

Aqui está uma visão geral dos valores comuns de AuthorizationType:

NONE
Descrição: Nenhuma autorização é necessária.
Caso de uso: Isso é usado para APIs acessíveis publicamente onde nenhuma autenticação é necessária. Qualquer cliente pode acessar esses endpoints sem restrições.
Exemplo: Um endpoint de API que fornece informações gerais como dados meteorológicos ou conteúdo público.
Descrição da API_KEY
: O cliente inclui uma chave de API nos cabeçalhos de solicitação ou parâmetros de URL.
Caso de uso: Normalmente usado para identificar aplicativos em vez de usuários. É uma maneira simples de controlar o acesso e monitorar o uso, mas não tem controle de acesso refinado.
Exemplo:
GET /resource HTTP/1.1
x-api-key: your-api-key-here

**Comment by huandu** [comment]
AFAIK, Facebook Graph API doesn't support `x-api-key` header right now. If you can find any official link on Facebook Developer site discussing this header, please share it to me. I'll investigate it. Thanks.
