### ISSUE TITLE
Is that package support facebook marketing api?

### ISSUE THREAD

**Issue by cention-mujibur-rahman** [huandu/facebook#38]
Hi Huandu,
I have a question for this package. Does this package support facebook marketing API's/Facebook adverts?
https://developers.facebook.com/docs/marketing-api/reference/v2.4
I found php and python package so wondering if your golang package support this too.
https://github.com/facebook/facebook-php-ads-sdk
https://github.com/facebook/facebook-python-ads-sdk

Thanks
Mujibur

**Comment by huandu** [comment]
No. I don't have chance to implement it as such API cannot be called by me individual developer.

**Comment by cention-mujibur-rahman** [comment]
Thanks for clarification. I am using your pkg so lets see If I can develop this.
I have to implement this to my application as well.

**Comment by huandu** [comment]
Great. It's highly appreciated If you can send PR to me later. :)

**Comment by huandu** [comment]
Close this issue and looking forward to your PR. :)

**Comment by cention-mujibur-rahman** [comment]
Hi Huandu,
I want to make sure you that your facebook package is good enough for facebook ads api as well.
I can fetch/send the ads api endpoints so no need new things to develop. 

Thanks
Mujibur

**Comment by huandu** [comment]
Frankly, I don't know what's the best way to integrate ads api to this package. I know format of ads api response is xml which is not supported by package result decoder. Direct integration, e.g. add a new method in Session, may not be suitable.

If you have any idea around integration, please let me know. If not, that's alright and leave this package as it is. :)

**Comment by cention-mujibur-rahman** [comment]
Huandu, No ads api's response is json.
No need to add new method in sessions as well.
url := fmt.Sprintf("%s/adcampaigns?fields=lifetime_budget,buying_type,name,optimization_goal,campaign_group_id,start_time,end_time,billing_event,is_autobid,campaign_status", adAccountId)
results, err := fb.BatchApi(userAccessToken, fb.Params{
	"relative_url": url,
})
log.Println(results[0].Get("body").(string))
The batchApi returns:
{"data":[{"lifetime_budget":"10000","buying_type":"AUCTION","name":"SELO, MY - 18+","optimization_goal":"PAGE_LIKES","campaign_group_id":"7777XX77777","start_time":"2015-08-11T10:31:10+0800","end_time":"2015-08-12T10:29:00+0800","billing_event":"IMPRESSIONS","is_autobid":true,"campaign_status":"ACTIVE","id":"XXXXXXXXXXX111"}],"paging":{"cursors":{"before":"NjAzMDgwODcyMTkxNwZDZD","after":"NjAzMDgwODcyMTkxNwZDZD"}}}

And when I authenticating with ads api its needed 1 more scope which is `ads_management or ads_read` 
then after exchanging the token I send this:
paramsForAds := rfb.Params{
		"method":       rfb.GET,
		"relative_url": "me/adaccounts",
}
into a batch request which responding adaccounts information.

**Comment by huandu** [comment]
Ah, I see.

One question: Why not use `fb.Get` to send out request? I think following code should work in your case.

```go
result, err := fb.Get(adAccountId + "/adcampaigns", fb.Params{
    "fields": "lifetime_budget,buying_type,name,optimization_goal,campaign_group_id,start_time,end_time,billing_event,is_autobid,campaign_status",
})
```

**Comment by cention-mujibur-rahman** [comment]
We can use that as well. :)
For me, I generally used to BatchApi function because Get returns map which I cant use to struct.

thanks

**Comment by huandu** [comment]
There is `Result#Decode` and `Result#DecodeField` to decode map data to struct directly. You can try it.

**Comment by revett** [comment]
@cention-mujibur-rahman @huandu - where did you get with using this pkg for the Marketing API?

**Comment by huandu** [comment]
@revett I don't quite understand your question. Can you please let me know more?

**Comment by revett** [comment]
@huandu no problem, were you able to re-purpose this package to extract data from Marketing API endpoints?

**Comment by huandu** [comment]
Per discussion in this thread, there is nothing special to extract data from Marketing API. You can use `fb.Get` to send request and use `Result` to parse result.

Here is a sample, which is copied from my previous post.

```go
result, err := fb.Get(adAccountId + "/adcampaigns", fb.Params{
    "fields": "lifetime_budget,buying_type,name,optimization_goal,campaign_group_id,start_time,end_time,billing_event,is_autobid,campaign_status",
})
```

**Comment by cention-mujibur-rahman** [comment]
Yeah, Huandu is right.
@revett Just use the package for same purpose as like others. Only difference is `adAccountId` on fb.Get.
Make sure when you authenticated the facebook with your system please check the scope `ads_management` is there or not.

**Comment by revett** [comment]
Thanks @huandu @cention-mujibur-rahman! 🎉

**Comment by Stefflan00** [comment]
@huandu when you use fb.Get is it then possible to do Paging? for example i retrieve Insights by ad level. time_increment 1 day ... so i get mutlipaging. Also i want to use a system user: https://developers.facebook.com/docs/marketing-api/businessmanager/systemuser/v2.9

I saw to use Paging you need a session with a App ID and Security Token. Its for me still also not clear if a System User needs an App ID and Security Token ... does anybody here knows how this works?

**Comment by huandu** [comment]
A session is required to make paging work. It's possible to create a session without App ID and secret. Here is a sample.

```go
session := &fb.Session{}
session.SetAccessToken("a-valid-access-token")
```
