### ISSUE TITLE
golang.org/x/oauth2

### ISSUE THREAD

**Issue by VojtechVitek** [huandu/facebook#40]
How can I use this pkg with golang.org/x/oauth2 properly?

```go
package main

import (
	"golang.org/x/oauth2"
	oauth2fb "golang.org/x/oauth2/facebook"

	"github.com/huandu/facebook"
)

func main() {
	
	conf := &oauth2.Config{
		ClientID:     "AppId",
		ClientSecret: "AppSecret",
		RedirectURL:  "CallbackURL",
		Scopes:       []string{"user_location"},
		Endpoint:     oauth2fb.Endpoint,
	}

	token, err := conf.Exchange(oauth2.NoContext, "code")

	client := conf.Client(oauth2.NoContext, tok)

	// Now, I want to pass the above client
	// (that already provides the AccessTokens)
	// into the facebook Session.
	// 
	// ... I tried:

	api := &facebook.Session{
		HttpClient: client,
		Version: "2.2",
	}

	err := api.Validate()  // <= returns "access token is not set" error
}
```

The question is... how do I create new Session with my own HttpClient and without any AccessToken (as my client's Transport already handles that)?

**Comment by VojtechVitek** [comment]
I ended up with this:

```go
app := facebook.New("AppId", "AppSecret")
api := app.Session("token")
api.Version = "v2.2"
api.HttpClient = client  // Client coming from golang.org/x/oauth2.
```

The only thing I'm not satisfied with is that this pkg forces me to provide AppId, AppSecret and Token. Which is what `golang.org/x/oauth2` client already handles for me.

Any suggestions? :)

**Comment by huandu** [comment]
You can use `Session#SetAccessToken` to set access token without having to create an App.

**Comment by VojtechVitek** [comment]
Here's what I'm saying:
I don't want to set AccessToken at all, as the `golang.org/x/oauth2` client's Transport already handles that for me :)

So, is it possible to use the API directly without setting AppId, AppSecret and AccessToken? Seems like most of the methods fail on checks like https://github.com/huandu/facebook/blob/ff27e4b6f04fe8b0d9b8c30ba549202ada899e52/session.go#L229-L232.

Thanks for your feedback:)

**Comment by VojtechVitek** [comment]
I guess I could use `session.Get("/me", Params{"fields": "id"})` directly, I will give it a shot.

**Comment by VojtechVitek** [comment]
Given
```go
	api := &facebook.Session{
		Version:    "v2.4",
		HttpClient: client,
	}
```

I can't use the following methods, as they return errors because of missing Session ID / AccessToken:
```go
	err := api.Validate()

	id, err := api.User()
```

But the following works :-)
```go
	res, err := api.Get("/me/accounts", getFbParams(url.Values{}))
```

**Comment by huandu** [comment]
OK. I get your point. I think it's reasonable to by-pass some access token checks when `Session#HttpClient` is set.

**Comment by VojtechVitek** [comment]
Yea, that'd do it. Thanks!

**Comment by huandu** [comment]
Please try latest code and let me know whether it works for you now.

**Comment by VojtechVitek** [comment]
That was fast, wow.. And it works now!

@huandu Thank you very much for such a fast resolution and for this project in general. Cheers.
