### ISSUE TITLE
ExchangeToken(token) method thowing error and the program terminated immediately!

### ISSUE THREAD

**Issue by cention-mujibur-rahman** [huandu/facebook#41]
Hi Huandu,
token, expires, err := fbApi.ExchangeToken(accessCode) 
ExchangeToken() is returning error like this: ` Error: field 'expires_in' doesn't exist in result.`
Reason is when you first time sent exchange token request then it works fine. Because first time facebook api return expires(expires can be `never expire` or `60 days as a timestamp`)
Say after getting response and then between 2-3 minutes I send ExchangeToken function again(As I was testing so I found) that time facebook doesn't send expires/expires_in anymore which turning the problem `expires_in` doesnt exists.
Is that in between your workaround the please fix. Otherwise I'll fix and send you the PR.
I think we should check DecodeField [ --> app.go] if `expires_in` or `expires` exists in results... :)

Thanks
Mujibur

**Comment by huandu** [comment]
It seems to be an undocumented behavior. What's your expected behavior? Is it OK to return 0 in this case?

**Comment by cention-mujibur-rahman** [comment]
Yes it should be ok. Because the main problem is program quit immediately. Thanks

**Comment by cention-mujibur-rahman** [comment]
Thanks
