### ISSUE TITLE
Support custom JSON unmarshaling and json.Unmarshaler interface in decoding

### ISSUE THREAD

**Issue by Perlence** [huandu/facebook#42]
Can I have a `http.Response` as result of GET request? I want to do custom JSON unmarshalling.

**Comment by huandu** [comment]
Can you please let me know your scenario? Why do you need to do custom JSON unmarshalling?

**Comment by Perlence** [comment]
I'm requesting user's feed `GET me/feed` and I need to decode objects in `data` into structs, that have field `CreatedTime` of type `pq.NullTime`. The way decoder works, it asserts that value at `created_time` must be an object.

I couldn't think of any better solution other than break my struct in two: one that has not null fields, and second that embeds first struct plus field `CreatedTime` of `pq.NullTime`. Then I decode post into first struct and embed it, then decode field `created_time` in second struct.

All this feels very clunky, I think it would be pretty convenient to implement `json.Unmarshaler` interface for my `NullTime`.

**Comment by huandu** [comment]
I see. If this package provides an interface `facebook.Unmarshaler` just like what json package implements, is it OK for you?

**Comment by Perlence** [comment]
I guess that would resolve the problem.

**Comment by huandu** [comment]
Fine. I'll implement it soon.

**Comment by huandu** [comment]
@Perlence I implemented in latest master code. Please take a look and have a try.

**Comment by Perlence** [comment]
Thank you!

When I implemented `json.Unmarshaler` interface for the whole struct it worked:

```go
type FeedResult struct {
	Data   []FacebookPost `json:"data"`
	Paging Paging         `json:"paging"`
}

type FacebookPost struct {
	ID          string      `json:"id" db:"id"`
	EntryID     int64       `json:"entry_id" db:"entry_id"`
	Message     string      `json:"message" db:"message"`
	Story       string      `json:"story" db:"story"`
	CreatedTime pq.NullTime `json:"created_time" db:"created_time"`
}

func (p *FacebookPost) UnmarshalJSON(data []byte) error {
	var aux struct {
		ID          string   `json:"id" db:"id"`
		Message     string   `json:"message" db:"message"`
		Story       string   `json:"story" db:"story"`
		CreatedTime NullTime `json:"created_time" db:"created_time"`
	}
	...
}

type NullTime struct{ pq.NullTime }

func (nt *NullTime) UnmarshalJSON(data []byte) error {
	t, err := time.Parse(dateFmt, string(data))
	if err != nil {
		return errors.Trace(err)
	}

	nt.Time = t
	nt.Valid = !t.IsZero()
	return nil
}
```

Yeah, I know there's `facebook.PagingResult`, but I must be able to set paging params myself, e.g. from DB. Anyways, I'm more than happy with such approach, it works fine.
But if I implement `json.Unmarshaler` only for a field, it doesn't work:

```go
type FeedResult struct {
	Data   []FacebookPost `json:"data"`
	Paging Paging         `json:"paging"`
}

type FacebookPost struct {
	ID          string   `json:"id" db:"id"`
	EntryID     int64    `json:"entry_id" db:"entry_id"`
	Message     string   `json:"message" db:"message"`
	Story       string   `json:"story" db:"story"`
	CreatedTime NullTime `json:"created_time" db:"created_time"`
}

type NullTime struct{ pq.NullTime }

func (nt *NullTime) UnmarshalJSON(data []byte) error {
	...
}
```

I get error "field 'data.0.created_time' is not a json object in result." I guess, that's expected.

**Comment by huandu** [comment]
It's a bug in my latest commit. I'll fix it soon.

**Comment by huandu** [comment]
@Perlence Please take a look at latest master code again. Thanks.

**Comment by Perlence** [comment]
Yep, it works, thanks :smile:

**Comment by huandu** [comment]
Glad to hear it. :smile:
