### ISSUE TITLE
always when i ask my feed the result is nil

### ISSUE THREAD

**Issue by pablopasten** [huandu/facebook#45]
always when i consult my feed the result is nil

`  resu, erro := fb.Get("/me/feed", fb.Params{
         "access_token": "CAAHH1zm0bMMBAAfZBznFlgdA7KAZCiJawqafa1SRZAr7I4ZAIgvBO4hcvz8T8yF5eA6tvNumQL3tsziCmTwawXq3MFuQXuLSZCnnZBNt0W1jcvxy3Vh5c3GCoz1VqTl4N7oJ2w7XtKVYtC1L6Ad8nAVCZBZAcoC6ZCip6HneBZC0piyw98vsXIcpgZB",
    })
`

**Comment by huandu** [comment]
What's the `erro`? You can try to convert it to `*fb.Error`, print all fields and post the result here.

**Comment by huandu** [comment]
Ping...

@padblopasten I'm looking forward to your input. The error message is quite important to help me to indicate your issue. Please take some time to post error message in this issue. Thanks.

**Comment by huandu** [comment]
Close it as I cannot investigate it without details.
