### ISSUE TITLE
Decode doesn't support interface for decoding custom types. 

### ISSUE THREAD

**Issue by nizsheanez** [huandu/facebook#47]
Here 2 ways to solve it: 
1. Have analog of json.Marshaler or even better 
2. Make possible to do json.Decode to custom type (not to facebook.Result) - now `Session.sendGetRequest` has this signature, but need something higher level and public.

**Comment by huandu** [comment]
The `Result#Decode` does support `json.Unmarshaler` for custom types. See https://github.com/huandu/facebook/blob/master/result.go#L424 for details.

I can update document later to make it clear.

**Comment by nizsheanez** [comment]
Oh, nice.
Do unmarshal struct, then marshal field and then unmarshal field looks like hack, but it's fine with me.
