### ISSUE TITLE
Encoded Field Parsers

### ISSUE THREAD

**Issue by kascote** [huandu/facebook#49]
I'm using the library to get information about some urls using this type of request

```
result, err := o.session.Get("", fb.Params{  
	"ids":    url_string,  
	"fields": "og_object{title, description,image,url}",  
})
```

The problem I see is that this return a dictionary structure (can check here https://goo.gl/A6m2Pm) where the key is the URL, that way I can't create structure to decode it, because the the key name is not a fixed value, it change on every request.
And I can't use the DecodeField either, because it try to parse the field using dot (1) and the key is an url.

May be I can make a Pull Request, but want to know what you think. I'm making some mistake ? There is other way to get the information? I think the current Result.Get is ok... may be check if the field starts with some url schemes (http, https) don't try to break it by dots. make sense ?

TIA

(1) https://github.com/huandu/facebook/blob/master/result.go#L102

**Comment by huandu** [comment]
`Result#GetField` method is designed for this case.

I don't think it's necessary to change `Result#Get`, which is a short-hand method for convenience in most cases, not all. And it doesn't make sense to check url schemes. Key of a result can be anything. URL is a special case and there can be numerous different patterns. It's not possible to handle all cases.

**Comment by huandu** [comment]
Feel free to reopen the issue if you have more questions. @kascote
