### ISSUE TITLE
Cannot decode into embedded struct

### ISSUE THREAD

**Issue by orian** [huandu/facebook#50]
The standard Json library could encode embedded:
https://play.golang.org/p/rA7yHzBYRk

In a case of Facebook' event when one gets it from user it may contain extra fields (rsvp_status) so I've tried to embed one into the other:

    type FbEvent struct {
      ID string
      Name string
    }

    type FbUserEvent struct {
      *FbEvent
      RsvpStatus string
    }

I've also tried with non-pointer `FbEvent`. In both cases the fields from `FbEvent` are empty.

**Comment by huandu** [comment]
It sounds like a reasonable feature request. It's not supported right now. I can implement it soon.

**Comment by orian** [comment]
I got it, was super easy. Will prepare a PR soon. Are you OK with it?

**Comment by huandu** [comment]
I have a better solution. :)

Thanks for your PR anyway.
