### ISSUE TITLE
Long live Access Token

### ISSUE THREAD

**Issue by cristianchaparroa** [huandu/facebook#52]
Hi, How can I create a Long Live Access token for Login with the normal token?

**Comment by huandu** [comment]
You can use [`App#ExchangeToken`](https://godoc.org/github.com/huandu/facebook#App.ExchangeToken) to get a long live token.

Here is the official HOW-TO document: https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension.

If you still have any question, feel free to reopen the issue.
