### ISSUE TITLE
FQL no longer available

### ISSUE THREAD

**Issue by mdempsky** [huandu/facebook#57]
According to https://developers.facebook.com/docs/technical-guides/fql:

> As of August 8 2016, FQL will no longer be available and cannot be queried. To migrate your app, use the API Upgrade Tool to see the Graph API calls you can make instead. Learn more about the API v2.1 migration.

Seems like the FQL functions can be removed.

**Comment by huandu** [comment]
OK. I'll do it later. Anyway, it's not an urgent issue.
