### ISSUE TITLE
How to call marketing API?

### ISSUE THREAD

**Issue by eric0324** [huandu/facebook#61]
Is that package support facebook marketing api?
If can , how to call it?
thank you!

**Comment by huandu** [comment]
Yes, it does. It's the same as calling other graph api.

Here is a sample to call [insights api](https://developers.facebook.com/docs/marketing-api/insights/v2.9).

```go
// curl -G \
//      -d "fields=impressions" \
//      -d "access_token=<ACCESS_TOKEN>" \
//         "https://graph.facebook.com/<API_VERSION>/<AD_OBJECT_ID>/insights"
fb.Version = "v2.9"
res, _ := fb.Post("/<AD_OBJECT_ID>/insights", fb.Params{
        "fields": "impressions",
        "access_token": "a-valid-access-token",
    })

// use res as usual.
```

**Comment by eric0324** [comment]
ok, thanks

**Comment by eric0324** [comment]
One more question....

If I want to define budget, billing, optimization, and duration

so I use it :https://developers.facebook.com/docs/marketing-api/buying-api?locale=en_US#ad-set-budget

There is one key is "targeting"...How do i use it?

**Comment by eric0324** [comment]
This is my code ...

```
fb.Version = "v2.9"
	res, _ := fb.Post("/act_438986589788036/adsets", fb.Params{
		"name":              "My Ad Set",
		"optimization_goal": "REACH",
		"billing_event":     "IMPRESSIONS",
		"bid_amount":        "2",
		"daily_budget":      "100",
		"campaign_id":       "........................",
		"targeting": [
			{
				"geo_locations": [{
				"countries": "US",
			}],
			}
		],
		"start_time":   "2017-04-24T18:23:34+0000",
		"end_time":     "2017-05-01T18:23:34+0000",
		"status":       "PAUSED",
		"access_token": "........................",
	})
```

But the code is wrong...

**Comment by huandu** [comment]
The param `targeting` is a JSON string. You can use `fb.Params` as a syntax candy to represent JSON structure in this case.

```go
params := fb.Params{
    "targeting": fb.Params{
        "geo_locations": fb.Params{
            "countries": []string{"US"},
        },
    },
    // ignore other keys...
}
```

**Comment by eric0324** [comment]
ok!!!Thank you very much!!

**Comment by eric0324** [comment]
ok,...I try to call AdCreative  to design my ad format..


```go
fb.Version = "v2.9"
	_, err := fb.Post("/act_XXXXXXXXXX/adcreatives", fb.Params{
		"name": "Sample",
		"object_story_spec": fb.Params{
			"link_data": fb.Params{
				"image_hash": "XXXXXXXXXX",
				"link":       "XXXXXXXXXX.com",
				"message":    "try it out",
			},
			"page_id": "XXXXXXXXXX",
		},
		"access_token": XXXXXXXXXX,
	})
```

but , It response "Invalid parameter"...That's why?

I think my parameters are correct and code is alse correct.

---

Sorry, I just started learning go..
I have a lot of questions, thank you for taking your time to guide me.

**Comment by huandu** [comment]
I'm not familiar with AdCreative API, so I cannot answer your question. According to the error message, I guess you sent wrong parameter to AdCreative API. It may be not a Go issue. I suggest you to use [Graph API Explorer](https://developers.facebook.com/tools/explorer/145634995501895/) to try to find a right query.
