### ISSUE TITLE
get picture in post return empty map

### ISSUE THREAD

**Issue by ipoj** [huandu/facebook#64]
I try to read posts from my page. I can get message and object_id from post in first part. But when i use object_id to make graph call for picture url, I get empty map result.
`
	session := fbApp.Session(accessToken)
	session.HttpClient = urlfetch.Client(c)
	res, _ := session.Get("/1469572976421082/posts", fb.Params{
		"fields": "created_time,message,object_id",
	})
	var posts []fb.Result
	err = res.DecodeField("data", &posts)

	if err != nil {
		log.Infof(c, "An error has happened %v", err)
		return
	}

	for _, p := range posts {
		if objid, ok := p["object_id"]; ok {
			ires, _ := session.Get("/"+objid.(string)+"/picture", nil)
			log.Infof(c, "ires: %v", ires)  ***<<=====This alway print empty map e.g. map[]***
		}
	}`

What i'm doing wrong? any idea?
I copy query string '/object_id/picture' and test in graph api explorer and it work fine

**Comment by ipoj** [comment]
ok, i've got error say 'cannot format facebook response. invalid character '\u0089' looking for beginning of value'.

**Comment by ipoj** [comment]
hmm, look like '/object_id/picture' is will return picture itself. I will close this issue.

**Comment by huandu** [comment]
Glad to hear that you've solved the problem. This url is a special case in Graph API. It's a 302 redirection rather than a json meta data.
