### ISSUE TITLE
Allow enabling Appsecret Proof for http client created by golang.org/x/oauth2

### ISSUE THREAD

**Issue by smasher164** [huandu/facebook#65]
Currently, creating a session from a client returned by the standard oauth2 library will work correctly for regular ("insecure") requests.
```golang
// Use OAuth2 client with session.
session := &fb.Session{
    Version:    "v2.4",
    HttpClient: client,
}

// Use session.
res, _ := session.Get("/me", nil)
```
However, the documentation for Session states that calling EnableAppsecretProof(true) "returns error if there is no App associasted with this Session."

I would like to know if it is possible to set the appsecretProof property if one is setting their own HttpClient. If not, can I request that this feature be added? Since the appsecretProof field is unexported and requires a non-nil App, I would be fine with being able to hash my own token/secret. Something like,
```golang
hash := hmac.New(sha256.New, []byte(secret))
hash.Write([]byte(token))
proof := hex.EncodeToString(hash.Sum(nil))
// Here, the user sets it manually
session.SetAppsecretProof(proof)
```
I would be willing to contribute. Thanks! :-)

**Comment by huandu** [comment]
My recommendation is to use `App` in this case. It's simple.

```go
// `app` should be a global variable created only once.
app := fb.NewApp(your_app_id, your_app_secret)

session := app.Session(your_access_token)
session.Version = "v2.4"
session.HttpClient = client
session.EnableAppsecretProof(true)

// Use session.
res, _ := session.Get("/me", nil)
```

BTW, if "v2.4" is the version for all sessions, you can set global variable `fb.Version` to "v2.4". It's the default version for all sessions without a specified version.

**Comment by smasher164** [comment]
Works perfectly. Thank you!
