### ISSUE TITLE
how does the post work theres no way to add post body

### ISSUE THREAD

**Issue by NikosEfthias** [huandu/facebook#67]
how does the post work there's no way to add post body

Post just requires endpoint and the parameters but where does the body go

**Comment by huandu** [comment]
The `params` is the body.

A Graph API request can be sent in either `GET` or `POST` method. See facebook document for details. https://developers.facebook.com/docs/graph-api/using-graph-api#basics

In the section `Making Large Requests`.

> Some Graph API endpoints can take parameters that are very large. If your requests end up being larger than a couple thousand characters, you may start seeing server errors since our servers will reject very large GET requests.
> 
> As a best practice, for large requests use a POST request instead of a GET request and add a method=GET parameter. If you do this, the POST will be interpreted as if it were a GET.

**Comment by NikosEfthias** [comment]
ah thanks that makes sense sorry for bothering :)

**Comment by huandu** [comment]
You're welcome. :)
