### ISSUE TITLE
Cannot get a session to work

### ISSUE THREAD

**Issue by Fyb3roptik** [huandu/facebook#68]
I know you dont cover it in the library, but in the README there is a deal about session. I am trying to use this to authenticate so I can post to my page via my server. 

This is not working for me
```golang
token, err := conf.Exchange(oauth2.NoContext, "code")
```
What do I need to put in place of code? How do I get this???? I have looked everywhere. Thanks

Also I will note I am attempting to do this as a server to server connection, so no login via web or anything like that as this will be a triggered post to a business fb page

**Comment by huandu** [comment]
The "code" is a temporary token returned by OAuth2 login callback. It's defined in OAuth2 spec, not facebook specific. If you don't implement OAuth2 login integration, you don't need the code.

In most common scenarios, we use facebook client side SDK (iOS, Android or JS) to get a valid access token directly. Once you get a token, send it to your server and use it to create a `Session` and call facebook API with the `Session`.

**Comment by huandu** [comment]
Feel free to re-open the issue if you still have any question. Thanks.
