### ISSUE TITLE
Marketing/Insights API integration 

### ISSUE THREAD

**Issue by kilmore** [huandu/facebook#70]
The facebook library is pretty awesome, but it seems to lack a good way to interact wit the marketing/insights API. When fb.Result is return there is a "Data" field that is an []interface{} that contains a map[string]interface{}.

I created a function that I am using in our system to pull the fields out of the map[string]interface{} (below).  I would like to create a new function(s) in this library that support this functionality, but being a new developer would love to have your input on its implementation (e.g. decodeInsights (...) and/or decodeInsight(..).

Thanks!

Dan

```go
func parseFacebookResult(result fb.Result, fieldName string) (float64, *Error) {
	//Loop over the facebook result "data" element as an array of interface
	for _, data := range result["data"].([]interface{}) {
		//loop over each element in the array as a map[string]interface and locate the field needed
		//The value of the field is a string so need to string convert to float 64
		for key, value := range data.(map[string]interface{}) {
			if key == fieldName {
				returnValue, err := strconv.ParseFloat(value.(string), 64)
				if err != nil {
					
					return 0, *err
				} else {
					return returnValue, nil
				}
			}
		}
	}
	err := errors.New("fieldName Not Found")
	return 0, *err
}
```

**Comment by huandu** [comment]
You can try to use `Result#DecodeField` instead. Remember that `Result` is a `map[string]interface{}`. You can decode a field into `Result` and use it to decode other field recursively.

```go
var data []Result
result.DecodeField("data", &data)

for _, d := range data {
    var someField string
    d.DecodeField("foo.bar", &someField)
    // use someField...
}
```

**Comment by huandu** [comment]
Close it as there is no more follow up. Feel free to reopen it for further discussion.
