### ISSUE TITLE
Video Upload

### ISSUE THREAD

**Issue by acochrane** [huandu/facebook#72]
Is there a right way to upload a video using the session.Post() method?

So far the the "upload_phase":"start" post works, but uploading the first chunk fails with this extended debugging info:
`map[error:map[fbtrace_id:C50g/HaHc+g message:Service temporarily unavailable type:OAuthException is_transient:true code:2 error_subcode:1363030 error_user_title:Video Upload Time Out error_user_msg:Your video upload timed out before it could be completed. This is probably because of a slow network connection or because the video you're trying to upload is too large. Please try again.] __debug__:map[__header__:map[X-Fb-Debug:[pIq0UxYHazOQbO0ymsHjew4B+S2s5SBZc5gmABYglX5y3JSiBAoirhbgiUsaEKXH2K2DxqvlgutX9+1iptZpCQ==] Date:[Sat, 29 Jul 2017 18:23:34 GMT] Pragma:[no-cache] X-Fb-Rev:[3190007] Facebook-Api-Version:[v2.9] Expires:[Sat, 01 Jan 2000 00:00:00 GMT] Www-Authenticate:[OAuth "Facebook Platform" "invalid_request" "Service temporarily unavailable"] Access-Control-Allow-Origin:[*] X-Fb-Trace-Id:[C50g/HaHc+g] Cache-Control:[no-store] Content-Type:[text/javascript; charset=UTF-8] Vary:[Accept-Encoding]] __proto__:HTTP/2.0]]
fb.UploadVideoError: Service temporarily unavailable`

I tested with the curl method defined [here](https://developers.facebook.com/docs/graph-api/video-uploads) and that works fine.

I'm trying to get video file chunk in the Params right for uploading the first chunk.
So far I have tried a pointer to a byte slice

`numBytes, readErr := file.ReadAt(chunkByteSlice, int64(startOffsetInt))`
`...`
`fb.Params{...,"video_file_chunk":chunkByteSlice}`

 and wrapping the byte slice in a buffer,

`chunkBuffer := bytes.NewBuffer(chunkByteSlice)`
`...`
`fb.Params{...,"video_file_chunk":chunkBuffer}`

**Comment by acochrane** [comment]
SOLUTION:

Must use the binaryData wrapper struct.
`chunkBuffer := bytes.NewBuffer(chunkByteSlice)`
`chunkBinaryData := fb.Data("inconsequential_file_name", chunkBuffer)
`...`
`fb.Params{...,"video_file_chunk":chunkBinaryData}`

Note that the filename is just used in the http form, it does not indicate that data will be read from a file.

**Comment by huandu** [comment]
You're right. The method `Data` is designed for this use case.
