### ISSUE TITLE
Errors aren't specific enough.

### ISSUE THREAD

**Issue by gfl-chris** [huandu/facebook#84]
Lack of sub-typing of the error returned by Session.Validate() means that call-sites have to resort to matching the error's string for certain key words like "expired" or "invalidated" or "confirmed" to handle handle/report Facebook-specific errors differently from, say, a network failure.

What do you think about matching the error string in the library and returning sub-typed errors?

**Comment by huandu** [comment]
If you are aware of the content of a Facebook error, you can try to convert the error to `facebook.Error`.

**Comment by huandu** [comment]
From my understanding, only Facebook-specific error should be handled by user code. Other errors, including a network failure, should be treated as an unexpected internal error. BTW, as you may know, the error returned by `http.DefaultClient.Do()`is not a named error. The only way to detect a network error is to match some keywords. It's wired. However, I cannot fix it in this library.

**Comment by huandu** [comment]
Feel free to reopen it if there is anything I need to do in this library.
