### ISSUE TITLE
How to read feed?

### ISSUE THREAD

**Issue by DeadNumbers** [huandu/facebook#85]
Hi! Why `fb.Get("/me/feed")` return only my posts on Facebook? Can I receive news as if I were using a web browser?

**Comment by huandu** [comment]
If my memory serves right, you need to grant `read_stream` permission to your app to read all posts. Try it.

**Comment by DeadNumbers** [comment]
I'm granted all permissions, but not found `read_stream`
![_2017-11-23_00-58-42](https://user-images.githubusercontent.com/9416005/33151554-98ebddf0-cfe9-11e7-8cc6-2f71abb5512f.png)

**Comment by huandu** [comment]
I do a little search work and find that `read_stream` is no longer supported since v2.4. You can try to use `/me/home` instead. BTW, I may not be the best one to answer you the question about facebook api usage. Stackoverflow is a better place for such question.
