### ISSUE TITLE
Panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by flemeur** [huandu/facebook#87]
Hi there!

First of all: Thank you for creating this awesome Go package! Until today I've had zero problems using it.

Unfortunately since the lastest release I've been getting panics from some of the requests made to the FB API. The code panics in [`addUsageInfo`](https://github.com/huandu/facebook/blob/master/session.go#L580) when res is nil. Maybe add a check for that case, like in [`addDebugInfo`](https://github.com/huandu/facebook/blob/master/session.go#L554)?

**Comment by huandu** [comment]
My fault. I'll fix it soon.

**Comment by flemeur** [comment]
Wauw, that was quick! Thanks! :smile:
