### ISSUE TITLE
Session's App Access Token can't be validated but Session.Get works

### ISSUE THREAD

**Issue by jensmcatanho** [huandu/facebook#89]
Hi, I'm trying to create a Session with an App in the code below.

```go
app := fb.New(appID, appSecret)
session := app.Session(app.AppAccessToken())

err := session.Validate()
if err != nil {
	if e, ok := err.(*fb.Error); ok {
		fmt.printf("[Message: %v] [Type: %v] [Code: %v] [Subcode: %v]",
				e.Message, e.Type, e.Code, e.ErrorSubcode)
	}
}
```
But I get the following error: `[Message: An active access token must be used to query information about the current user.] [Type: OAuthException] [Code: 2500] [Subcode: 0]`

However, when my application later executes the following code:
```go
params := fb.Params{
	"fields":       "friends",
}

res, err := f.Session.Get(fmt.Sprintf("/%d", id), params)
```
`err` is nil and I'm able to use `res.Decode()` to get the information I wanted even though my access token was said to be invalid by session.Validate().

If the access token was invalid I shouldn't be able to call Get with success. So, I suppose this is an unexpected behaviour.

**Comment by huandu** [comment]
The `session.Validate()` is designed to validate a user access token. If a token passes the validation, it's valid to get `/me` object and related edges.

If you just want to know whether the token can be used for API not related to `/me`, use `session.Inspect()` instead.

**Comment by huandu** [comment]
BTW, an app access token is a special token which is designed for app management and should not be used to retrieve user data. Try not to use such token if possible.

**Comment by jensmcatanho** [comment]
Thanks, I was unaware of the difference between the user access token and the app access token. However, I still have a question. How do I get the user access token? Is it when the user authorizes my app?

**Comment by huandu** [comment]
If you have an app, you should use Facebook app SDK which provides basic login and authentication  APIs. After login, you can get a user access token. You can read facebook document to learn details.

https://developers.facebook.com/docs/ios/
https://developers.facebook.com/docs/android/

**Comment by jensmcatanho** [comment]
I understand now, thanks for the information!
