### ISSUE TITLE
Fields with space in key?

### ISSUE THREAD

**Issue by robbiet480** [huandu/facebook#93]
Sometimes the Insights API will return data like this:

```json
{
  "values": [
    {
      "value": {
        "other clicks": 874,
        "photo view": 3,
        "link clicks": 2007
      }
    }
  ],
  "name": "post_consumptions_by_type",
  "period": "lifetime",
  "id": "post_id/insights/post_consumptions_by_type/lifetime"
}
```

Yet no matter what I do, I can't get those values to marshal into JSON whether I use the Facebook or JSON tags. I can see the values are coming in when I print the raw Result though. Any ideas how to get around or fix this? I'm attempting to Marshal to this struct:

```go
type ConsumptionTypes struct {
	OtherClicks int64 `json:"other clicks"`
	PhotoViews  int64 `json:"photo view"`
	LinkClicks  int64 `json:"link clicks"`
}

type ConsumptionTypeInsights struct {
	Values []struct {
		ConsumptionTypes `facebook:"value"`
	} `facebook:"values"`
	Name   string `facebook:"name"`
	Period string `facebook:"period"`
	ID     string `facebook:"id"`
}
```

**Comment by huandu** [comment]
Try to use `facebook` to replace `json` in struct field tag. It should work fine.

**Comment by robbiet480** [comment]
I did try that previously. It didn’t work.

**Comment by huandu** [comment]
I wrote a test against this. I find it's because this package doesn't support anonymous field very well. It works if the field `ConsumptionTypes` has a whatever name.

I'll investigate the root cause and fix it. Before that, you can name the anonymous field as a workaround.
