### ISSUE TITLE
Why does Session.graph() always creates a post request?

### ISSUE THREAD

**Issue by jensmcatanho** [huandu/facebook#94]
When creating a Get request using a session, the following functions are called:
`fb.Session.Get()`
`session.Api()`
`session.graph()`
`session.sendPostRequest()`

Why `session.sendPostRequest()` is called no matter what Method is passed? Why is `session.sendGetRequest()` not called in this case?

**Comment by huandu** [comment]
Facebook API doesn't really use HTTP method to detect API method. Instead, it uses "method" param which is specified either in query string or form-url-encoded POST body. As `session.sendPostRequest()` works in all cases including uploading files but `session.sendGetRequest()` doesn't, I choose to use one method for all graph api to make code simpler.
